# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_port.xdc

# Block Designs: bd/arty_8bit_colour/arty_8bit_colour.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour || ORIG_REF_NAME==arty_8bit_colour} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_clk_wiz_0/arty_8bit_colour_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_clk_wiz_0 || ORIG_REF_NAME==arty_8bit_colour_clk_wiz_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_vga_pmod_0_0/arty_8bit_colour_vga_pmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_vga_pmod_0_0 || ORIG_REF_NAME==arty_8bit_colour_vga_pmod_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_xlconcat_0_0/arty_8bit_colour_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_xlconcat_0_0 || ORIG_REF_NAME==arty_8bit_colour_xlconcat_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_xlslice_0_0/arty_8bit_colour_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_xlslice_0_0 || ORIG_REF_NAME==arty_8bit_colour_xlslice_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_consts_0_0/arty_8bit_colour_consts_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_consts_0_0 || ORIG_REF_NAME==arty_8bit_colour_consts_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_pixel_mux_0_0/arty_8bit_colour_pixel_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_pixel_mux_0_0 || ORIG_REF_NAME==arty_8bit_colour_pixel_mux_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_char_rom_0_0/arty_8bit_colour_char_rom_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_char_rom_0_0 || ORIG_REF_NAME==arty_8bit_colour_char_rom_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_xlslice_1_0/arty_8bit_colour_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_xlslice_1_0 || ORIG_REF_NAME==arty_8bit_colour_xlslice_1_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_vid_ram_0_0/arty_8bit_colour_vid_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_vid_ram_0_0 || ORIG_REF_NAME==arty_8bit_colour_vid_ram_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_vga_timing_0_0/arty_8bit_colour_vga_timing_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_vga_timing_0_0 || ORIG_REF_NAME==arty_8bit_colour_vga_timing_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_ila_0_0/arty_8bit_colour_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_ila_0_0 || ORIG_REF_NAME==arty_8bit_colour_ila_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_spi_0_0/arty_8bit_colour_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_spi_0_0 || ORIG_REF_NAME==arty_8bit_colour_spi_0_0} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_vid_ram_0_1/arty_8bit_colour_vid_ram_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_vid_ram_0_1 || ORIG_REF_NAME==arty_8bit_colour_vid_ram_0_1} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_vid_ram_0_2/arty_8bit_colour_vid_ram_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_vid_ram_0_2 || ORIG_REF_NAME==arty_8bit_colour_vid_ram_0_2} -quiet] -quiet

# IP: bd/arty_8bit_colour/ip/arty_8bit_colour_xlslice_2_0/arty_8bit_colour_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty_8bit_colour_xlslice_2_0 || ORIG_REF_NAME==arty_8bit_colour_xlslice_2_0} -quiet] -quiet

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/arty_8bit_colour_ooc.xdc
