# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/tmp/arty_vga/arty_vga.srcs/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_ila_0_0/arty_8bit_colour_ila_0_0.xci
# IP: The module: 'arty_8bit_colour_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_ila_0_0/arty_8bit_colour_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/tmp/arty_vga/arty_vga.srcs/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_ila_0_0/arty_8bit_colour_ila_0_0.xci
# IP: The module: 'arty_8bit_colour_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_ila_0_0/arty_8bit_colour_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
