# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/tmp/arty_vga/arty_vga.srcs/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_clk_wiz_0/arty_8bit_colour_clk_wiz_0.xci
# IP: The module: 'arty_8bit_colour_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_clk_wiz_0/arty_8bit_colour_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_clk_wiz_0/arty_8bit_colour_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_clk_wiz_0/arty_8bit_colour_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/tmp/arty_vga/arty_vga.srcs/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_clk_wiz_0/arty_8bit_colour_clk_wiz_0.xci
# IP: The module: 'arty_8bit_colour_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_clk_wiz_0/arty_8bit_colour_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_clk_wiz_0/arty_8bit_colour_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/tmp/arty_vga/arty_vga.gen/sources_1/bd/arty_8bit_colour/ip/arty_8bit_colour_clk_wiz_0/arty_8bit_colour_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_8bit_colour_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
